#!/usr/bin/lua

local site = require 'gluon.site_config'
local fs = require 'nixio.fs'

local sitecode = site.site_code

if sitecode == 'ff3l-hoho' then
  domain = 'hoho'
elseif sitecode == 'ff3l-wtk' then
  domain = 'wtk'
elseif sitecode == 'ff3l-wald' then
  domain = 'wald'
elseif sitecode == 'ff3l-wiese' then
  domain = 'wiese'
elseif sitecode == 'ff3l-loe' then
  domain = 'loe'
elseif sitecode == 'ff3l-3land' then
  domain = '3land'
elseif sitecode == 'ff3l-ref' then
  domain = 'ref'
elseif sitecode == 'ff3l-test' then
  domain = 'test'
elseif sitecode == 'ff3l-swb' then
  domain = 'swb'
elseif sitecode == 'ff3l-nalb' then
  domain = 'nalb'
elseif sitecode == 'ff3l-ng' then
  domain = 'ffng'
else
  domain = 'default'
end

local content = 'config core \'core\'\n\toption domain \'' .. domain .. '\'\n'

fs.writefile('/etc/config/gluon', content)
